#!/bin/bash
# Output and error (also --output, --error):
#SBATCH -o ./%x.%j.out
#SBATCH -e ./%x.%j.err
# Initial working directory (also --chdir):
#SBATCH -D ./
# Notification and type
#SBATCH --mail-type=END
# Wall clock limit:
#SBATCH --no-requeue
# Number of nodes - set via cmd
# Setup of execution environment
#SBATCH --export=NONE
#SBATCH --get-user-env

executable="$1"
options="$2"
lock_file="$3"

mpirun $executable $options

rm $lock_file
