name: Indent

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        exclude: ''
        extensions: 'cc,h'
        clangFormatVersion: 11
        inplace: true
    - name: code-formating
      run: |
        git diff
        git diff-files --quiet || exit $?
